routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('course', 'CourseController');


Route::resource('assignments','assignmentsController');

Route::resource('student', 'studentController');

Route::resource('exam', 'ExamController');

//Route::get('/student1', ['uses'=> 'studentController@index']);

Route::get('/st', function() {
    return view('Student.create');

});
    Route::get('/course_home', function () {
        return view('course.courseHome');
    });


    Route::get('/show', function () {
        return view('assignments.show');

    });

    Route::get('/st1', function () {
        return view('Student.index');
    });


    Route::resource('instructor', 'InstructorController');


// Route::get('/instructor', ['uses'=>'InstructorController@index']);

// Route::get('/createInstructor', function(){
//     return view('instructor.create');
// });

// Route::get('/createInstructor/{id}', function(){
//     return view('instructor.create');
// });

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $table = "student";

    public $primarykey="id";

    protected  $guarded = ['id'];
}

app/Http/Controllers/studentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Student;
use DB;

class studentController extends Controller
{
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $student = Student::all();

        return view('Student.student',compact('student'));
    }

    /**
     * Show the form for creating a new resource. 
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Student.create')->with('alert', 'Added Successfully');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

      return DB::transaction(function() use($request){

            $contact = new Student([
           
           
            'firstname' => $request->get('firstname'),
            'lastname'  => $request->get('lastname'),
            'address'   => $request->get('address'),
            'email'     => $request->get('email'),
            'phoneNo'   => $request->get('phoneNo')
            

            ]);

            $contact->save();
    
            return redirect('/student/show')->with('alert', ' Added Successfully');
        });
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $student = Student::all();
        return view('Student.show',compact('student'));
    }
    

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $student = Student::findOrFail($id);
        return view('Student.edit',compact('student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //

        $student = Student::findOrFail($id);

        $student->firstname = $request->get('firstname');
        $student->lastname = $request->get('lastname');
        $student->address = $request->get('address');
        $student->email = $request->get('email');
        $student->phoneNo = $request->get('phoneNo');

        $student->save();

        return redirect('/student/show');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $student = student::findOrFail($id);
        $student->delete();

        return redirect('/student/show');
    }
}

resources/views/Student/create.blade.php
<!DOCTYPE html>
<meta name="csrf-token" content="{{ csrf_token() }}">
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Student Registration </title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

    <!-- Styles -->
    <style>
        html, body {
            background-color: #fff;
            color: #636b6f;
            font-family: 'Nunito', sans-serif;
            font-weight: 200;
            height: 100vh;
            margin: 0;
        }

        .full-height {
            height: 100vh;
        }

        .flex-center {
            align-items: center;
            display: flex;
            justify-content: center;
        }

        .position-ref {
            position: relative;
        }

        .top-right {
            position: absolute;
            right: 10px;
            top: 18px;
        }


        .title {
            font-size: 84px;
        }

        .links > a {
            color: #636b6f;
            padding: 0 25px;
            font-size: 13px;
            font-weight: 600;
            letter-spacing: .1rem;
            text-decoration: none;
            text-transform: uppercase;
        }

        .m-b-md {
            margin-bottom: 30px;
        }
        input[type=text], select {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        input[type=submit] {
            width: 100%;
            background-color: #4CAF50;
            color: white;
            padding: 14px 20px;
            margin: 8px 0;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        input[type=submit]:hover {
            background-color: #45a049;
        }

        div {
            border-radius: 5px;
            background-color: #f2f2f2;
            padding: 20px;
        }
        #submit {
            background-color: #008CBA; /* Green */
            border: none;
            color: white;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
        }
    </style>
</head>
<body>

        <div class="flex-center position-ref full-height">

        <div class="top-right links">


            <a href="{{ url('/student') }}">Student Registration</a>
            <a href="">Instructor Registration</a>
            <a href="{{ url('/course') }}">Course Registration</a>
            <a href="{{ url('/course') }}">Exam Registration</a>
            <a href="{{ url('/assignments') }}">Assignments Registration</a>
              



        </div>

            <div>

                <br>
                <br>
                <h2><marquee>Student Registration</marquee></h2>

            <form action="{{ route('student.store') }}" method ="POST">
                            
                          {{ csrf_field() }}
                          
                <label for = "firstname">First Name:</label>
                <input type="text" class="form-control" name="firstname" required ><br><br>

                <label for = "lastname">Last Name:</label>
                <input type="text" class="form-control" name="lastname" required><br><br>

                <label for = "address">Address: </label>
                <input type="text" class="form-control" name="address" required><br><br>

                <label for = "email">Email:</label>
                <input type="text" required class="form-control" name="email" ><br><br>

                <label for = "phoneNo">Phone no:</label>
                <input type="text" class="form-control" name="phoneNo" required><br><br>

                <input type="submit"  id ="submit" align="center" value="Submit" onclick="">


            </form>
            </div>

        </div>
</body>
</html>

resources/views/Student/edit.blade.php
@extends('layout')
@section('content')

    @if(session()->has('jsAlert'))
        <script>
            alert({{ session()->get('jsAlert') }});
        </script>
    @endif
    <div class="container">

    <form style="margin-left: 400px; margin-right: 400px; margin-top: 100px" method="POST" action="{{ route('student.update', $student->id) }}">

        <h1 class="title" style="text-align: center"> Edit Student </h1>
  
        @method('PATCH')
        @csrf

        <div class="field">

            <label class="label" for="name">First Name </label>

            <div class="control">

                <input type="text" class="input" name="firstname" placeholder="" value="{{ $student->firstname }}" required>

            </div>

        </div>

        <div class="field">

            <label class="label" for="sport">Last Name </label>

            <div class="control">

                <input type="text" class="input" name="lastname" placeholder="" value="{{ $student->lastname }}" required>


            </div>

        </div>
        <div class="field">

            <label class="label" for="sport">Address</label>

            <div class="control">

                <input type="text" class="input" name="address" placeholder="" value="{{ $student->address }}" required>


            </div>

        </div>
        <div class="field">

            <label class="label" for="sport">Email </label>

            <div class="control">

                <input type="text" class="input" name="email" placeholder="" value="{{ $student->email }}" required>


            </div>

        </div>

        <div class="field">

        <label class="label" for="sport">Phone No </label>

        <div class="control">

        <input type="text" class="input" name="phoneNo" placeholder="" value="{{ $student->phoneNo }}" required>


        </div>

        </div>


        <div class="field">

            <div class="control">

                <button style="width: 100%" type="submit" class="button is-link">Update Student</button>

            </div>

        </div>

    </form>

        <form style="margin-left: 400px; margin-right: 400px; margin-top: 10px" method="POST" action="{{ route('student.destroy', $student->id) }}">

            @method('DELETE')
            @csrf


            <div class="field">

                <div class="control">

                    <button style="width: 100%" type="submit" class="button is-link">Delete Student</button>

                </div>

            </div>

        </form>

    </div>
@endsection

resources/views/Student/show.blade.php
@extends('layout')

@section('content')

    <!DOCTYPE html>
<html lang="">
<head>
    @if(session()->has('jsAlert'))
        <script>
            alert({{ session()->get('jsAlert') }});
        </script>
    @endif
    <style>
        a:link, a:visited {
            background-color: #008CBA;
            color: white;
            padding: 14px 25px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
        }

        a:hover, a:active {
            background-color: red;
        }
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
    <title></title>
</head>
<br style="margin-left: 400px; margin-right: 400px; margin-top: 100px">

<br>

<h1 class="title" style="text-align: center">Details of Students </h1>

@foreach ($student as $Student)

<table>

    <tr>
        <td>Student ID: {{ $Student->id}}</td>
    </tr>
    <tr>
        <td>First Name: {{ $Student->firstname }}</td>
    </tr>
    <tr>
        <td>Last Name: {{ $Student->lastname }}</td>
    </tr>
    <tr>
        <td>Address: {{ $Student->address }}</td>
    </tr>
    <tr>
        <td>Email: {{ $Student->email }}</td>
    </tr>
    <tr>
        <td>Phone No: {{ $Student->phoneNo }}</td>
    </tr>
    <tr>
        <td>
            <a style=" padding: 5px; width:130px; height:35px" href="{{ $Student->id }}/edit">Edit Student</a>
        
           
            <form style=" margin-top: 10px" method="POST" action="{{ route('student.destroy', $Student->id) }}">

        @method('DELETE')
        @csrf


        <div class="field">

        <div class="control">

        <button style="width:130px; height:35px" type="submit" class="button is-link">Delete Student</button>

        </div>

        </div>

        </form>

        </td>
    </tr>
</table>
<br>
<br>
<br>
@endforeach

@endsection

</body>
</html>

resources/views/Student/student.blade.php
@extends('layout')

@section('content')

<!DOCTYPE html>
<html lang="">
<head>

    <title></title>
</head>
<style>

    .container
    {
        padding-bottom: 20px;
        background-color: #ccddff;
    }


</style>
@if(session()->has('jsAlert'))
    <script>
        alert({{ session()->get('jsAlert') }});
    </script>
@endif
<body>
<div class="container">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6" style="margin-left: 500px; margin-top: 100px;">
            <br>
            <h1 class="title">Student  - 2019</h1>

            <br/>
            <form action="{{ route('student.create') }}">
                <div class="field">
                    <div class="control">
                        <button type="submit" class="button is-link" style="margin-left: 100px; width: 200px; height:40px">Create New Student</button>
                    </div>
                </div>
            </form>
            <br/>
            <button type="submit" class="button is-link" style="margin-left: 100px; width: 200px; height:40px">
            <a style=" color: white" href="student/show">View Details</a>
            </button>

        </div>
    </div>
</div>
</body>
</html>


@endsection