routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('course', 'CourseController');


Route::resource('assignments','assignmentsController');

Route::resource('student', 'studentController');

Route::resource('exam', 'ExamController');

//Route::get('/student1', ['uses'=> 'studentController@index']);

Route::get('/st', function() {
    return view('Student.create');

});
    Route::get('/course_home', function () {
        return view('course.courseHome');
    });


    Route::get('/show', function () {
        return view('assignments.show');

    });

    Route::get('/st1', function () {
        return view('Student.index');
    });


    Route::resource('instructor', 'InstructorController');


// Route::get('/instructor', ['uses'=>'InstructorController@index']);

// Route::get('/createInstructor', function(){
//     return view('instructor.create');
// });

// Route::get('/createInstructor/{id}', function(){
//     return view('instructor.create');
// });

app/exam.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class exam extends Model
{
    //
    public $table = "exams";
}

app/Http/Controllers/ExamController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\exam;

class ExamController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    
        return view('exam.exam');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('exam.exam');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $Exam = new exam();

        $Exam->subName = $request->get('subName');
        $Exam->subId = $request->get('subId');
        $Exam->date = $request->get('date');
        $Exam->time = $request->get('time');
        $Exam->venue = $request->get('venue');
   
        $Exam->save();

        return redirect('/exam');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        $exam = exam::all();

        return view('exam.showExam',compact('exam'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $exam = exam::findOrFail($id);
        return view('exam.editExam',compact('exam'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $exam = exam::findOrFail($id);

        $exam->subName = $request->get('subName');
        $exam->subId = $request->get('subId');
        $exam->date = $request->get('date');
        $exam->time = $request->get('time');
        $exam->venue = $request->get('venue');

        $exam->save();

        return redirect('/exam/showExam');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $exam = exam::findOrFail($id);
        $exam->delete();

        return redirect('/exam/showExam');
    }
}

resources/views/exam/editExam.blade.php
@extends('layout')
@section('content')

    @if(session()->has('jsAlert'))
        <script>
            alert({{ session()->get('jsAlert') }});
        </script>
    @endif
    <div class="container">

    <form style="margin-left: 400px; margin-right: 400px; margin-top: 100px" method="POST" action="{{ route('exam.update', $exam->id) }}">

        <h1 class="title" style="text-align: center"> Edit Exam Details </h1>

        @method('PATCH')
        @csrf

        <div class="field">
            <label class="label" for="name">Subject Name </label>
            <div class="control">
                <input type="text" class="input" name="subName" placeholder="" value="{{ $exam->subName }}" required>
            </div>
         </div>

        <div class="field">
            <label class="label" for="sport">Subject ID </label>
            <div class="control">
                <input type="text" class="input" name="subId" placeholder="" value="{{  $exam->subId }}" required>
            </div>
        </div>

        <div class="field">
            <label class="label" for="sport">Date </label>
            <div class="control">
                <input type="text" class="input" name="date" placeholder="" value="{{ $exam->date }}" required>
            </div>
        </div>

        <div class="field">
            <label class="label" for="sport">Time </label>
            <div class="control">
                <input type="text" class="input" name="time" placeholder="" value="{{ $exam->time }}" required>
            </div>
        </div>

        <div class="field">
            <label class="label" for="sport">Venue </label>
            <div class="control">
                <input type="text" class="input" name="venue" placeholder="" value="{{ $exam->venue }}" required>
            </div>
        </div>

        <div class="field">
            <div class="control">
                <button style="width: 100%" type="submit" class="button is-link"> Update Details</button>
            </div>
        </div>
        
    </form>

        <form style="margin-left: 400px; margin-right: 400px; margin-top: 10px" method="POST" action="{{ route('exam.destroy', $exam->id) }}">

            @method('DELETE')
            @csrf

            <div class="field">
                <div class="control">
                    <button style="width: 100%" type="submit" class="button is-link">Delete Exam Details</button>
                </div>
            </div>

        </form>
    </div>
@endsection

resources/views/exam/exam.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Exam Registration </title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

    <!-- Styles -->
    <style>
        html, body {
            background-color: #ffffff;
            color: #636b6f;
            font-family: 'Nunito', sans-serif;
            font-weight: 200;
            height: 100vh;
            margin: 0;
        }

        .full-height {
            height: 100vh;
        }

        .flex-center {
            align-items: center;
            display: flex;
            justify-content: center;
        }

        .position-ref {
            position: relative;
        }

        .top-right {
            position: absolute;
            right: 10px;
            top: 18px;
        }


        .title {
            font-size: 84px;
        }

        .links > a {
            color: #636b6f;
            padding: 0 25px;
            font-size: 13px;
            font-weight: 600;
            letter-spacing: .1rem;
            text-decoration: none;
            text-transform: uppercase;
        }

        .m-b-md {
            margin-bottom: 30px;
        }
        input[type=text], select {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        input[type=submit] {
            width: 100%;
            background-color: #4CAF50;
            color: white;
            padding: 14px 20px;
            margin: 8px 0;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        input[type=submit]:hover {
            background-color: #45a049;
        }
        div {
            border-radius: 5px;
            background-color: #f2f2f2;
            padding: 20px;
        }
        #submit {
            background-color: #008CBA; /* Green */
            border: none;
            color: white;
            width: 150px;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
        }
    </style>
</head>
<body>

<div class="flex-center position-ref full-height">

    <div class="top-right links">
                <a href="">Student Registration</a>
                <a href="">Instructor Registration</a>
                <a href="{{ url('/course') }}">Course Registration</a>
                <a href="{{ url('/assignments') }}">Assignments</a>
                <a href="{{ url('/exam') }}">Exam Registration</a>
    </div>

    <div>
        <br>
        <br>
        <h1>Exam Registration</h1>

        <form action="{{ route('exam.store') }}" method ="POST">
        {{ csrf_field() }}

            <label for = "SubName">Subject Name</label>
            <input type="text" class="form-control" name="subName" required><br>

            <label for = "SubId">Subject ID</label>
            <input type="text" class="form-control" name="subId" required><br>

            <label for = "Date">Date</label>
            <input type="text" class="form-control" name="date" required><br>

            <label for = "Time">Time</label>
            <input type="text" class="form-control" name="time" required ><br>

            <label for = "Venue">Venue</label>
            <input type="text" class="form-control" name="venue" required ><br>

            <input type="submit"  id ="submit" align="center" value="Submit" onclick="">

            <button type="submit" class="button is-link" style="margin-left: 100px; width: 195px; height:60px">
            <a href="exam/showExam">View Details</a>
            </button>

        </form>
    </div>

</div>
</body>
</html>

resources/views/exam/showExam.blade.php
@extends('layout')

@section('content')

    <!DOCTYPE html>
<html lang="">
<head>
    @if(session()->has('jsAlert'))
        <script>
            alert({{ session()->get('jsAlert') }});
        </script>
    @endif
    <style>

        a:link, a:visited {
            background-color: #008CBA;
            color: white;
            padding: 14px 25px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
        }

        a:hover, a:active {
            background-color: blue;
        }

        table {
            font-family: arial, sans-serif;
            width: 50%;
            align : center;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: white;
        }
        
    </style>
    <title></title>
</head>

<br style="margin-left: 400px; margin-right: 400px; margin-top: 100px">

<br>

<h1 class="title" style="text-align: center"> Exam Details </h1>

@foreach ($exam as $exam)

<table>

    <tr>
        <td>Subject Name : {{ $exam->subName}}</td>
    </tr>
    <tr>
        <td>Subject ID : {{ $exam->subId }}</td>
    </tr>
    <tr>
        <td>Date : {{ $exam->date }}</td>
    </tr>
    <tr>
        <td>Time : {{ $exam->time }}</td>
    </tr>
    <tr>
        <td>venue : {{ $exam->venue }}</td>
    </tr>
</table>


<tr>
    <a style=" padding: 10px;" href="{{ $exam->id }}/edit">Edit Exam</a>

    <a style=" padding: 10px;" href="#" >Delete Exam</a>
</tr>

<br>
<br>
<br>
@endforeach

@endsection

</body>
</html>