routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('course', 'CourseController');


Route::resource('assignments','assignmentsController');

Route::resource('student', 'studentController');

Route::resource('exam', 'ExamController');

//Route::get('/student1', ['uses'=> 'studentController@index']);

Route::get('/st', function() {
    return view('Student.create');

});
    Route::get('/course_home', function () {
        return view('course.courseHome');
    });


    Route::get('/show', function () {
        return view('assignments.show');

    });

    Route::get('/st1', function () {
        return view('Student.index');
    });


    Route::resource('instructor', 'InstructorController');


// Route::get('/instructor', ['uses'=>'InstructorController@index']);

// Route::get('/createInstructor', function(){
//     return view('instructor.create');
// });

// Route::get('/createInstructor/{id}', function(){
//     return view('instructor.create');
// });

app/Http/Controllers/InstructorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\InstructorData;
use Illuminate\Support\MessageBag;
use Illuminate\Support\Facades\session;
use DB;

class InstructorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('Instructor.Instructor');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $Instructor = InstructorData::all();
        return view('Instructor.create', compact('Instructor'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return DB::transaction(function() use($request){

            $contact = new InstructorData([
           
           
            'firstname' => $request->get('firstname'),
            'lastname'  => $request->get('lastname'),
            'address'   => $request->get('address'),
            'email'     => $request->get('email'),
            'phoneNo'   => $request->get('phoneNo'),
            'subjects'  => $request->get('subjects')

            ]);

            $contact->save();
    
            return redirect('/instructor/show');

        });
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $instructor = InstructorData::all();

        return view('Instructor.show',compact('instructor'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Instructor = InstructorData::findOrFail($id);
        return view('Instructor.edit',compact('Instructor'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $Instructor = InstructorData::findOrFail($id);

        $Instructor->firstname = $request->get('firstname');
        $Instructor->lastname  = $request->get('lastname');
        $Instructor->address   = $request->get('address');
        $Instructor->email     = $request->get('email');
        $Instructor->phoneNo   = $request->get('phoneNo');
        $Instructor->subjects  = $request->get('subjects');

        $Instructor->save();
        return redirect('/instructor/show');

        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // $Instructor = InstructorData::findOrFail($id);
        // $Instructor->delete();

        // return redirect() ->route('Instructor.show')->with('success', 'Remove Instructor Details ');

        $Instructor = InstructorData::findOrFail($id);
        $Instructor->delete();

        return redirect('/instructor/show');
    }
}

resources/views/Instructor/Instructor.blade.php
@extends('layout')

@section('content')

<!DOCTYPE html>
<html lang="">
<head>

    <title></title>
</head>
<style>

    .container
    {
        padding-bottom: 20px;
        background-color: #ccddff;
    }


</style>
@if(session()->has('jsAlert'))
    <script>
        alert({{ session()->get('jsAlert') }});
    </script>
@endif
<body>
<div class="container">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6" style="margin-left: 500px; margin-top: 100px;">
            <br>
            <h1 class="title">Instructor Home</h1>

            <br/>
            <form action="{{ url('/instructor/create') }}">
                <div class="field">
                    <div class="control">
                        <button type="submit" class="button is-link" style="margin-left: 100px">Insert new Instructor</button>
                    </div>
                </div>
            </form>
            <br/>
            <form action="{{ url('/instructor/show') }}">
            <button type="submit" class="button is-link" style="margin-left: 100px; width: 195px">
            <a style=" color: white;">View Instructor Details</a>
            </button>

        </div>
    </div>
</div>
</body>
</html>


@endsection

resources/views/Instructor/create.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Instructor Registration </title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

    <!-- Styles -->
    <style>
        html, body {
            background-color: #fff;
            color: #636b6f;
            font-family: 'Nunito', sans-serif;
            font-weight: 200;
            height: 100vh;
            margin: 0;
        }

        .full-height {
            height: 100vh;
        }

        .flex-center {
            align-items: center;
            display: flex;
            justify-content: center;
        }

        .position-ref {
            position: relative;
        }

        .top-right {
            position: absolute;
            right: 10px;
            top: 18px;
        }


        .title {
            font-size: 84px;
        }

        .links > a {
            color: #636b6f;
            padding: 0 25px;
            font-size: 13px;
            font-weight: 600;
            letter-spacing: .1rem;
            text-decoration: none;
            text-transform: uppercase;
        }

        .m-b-md {
            margin-bottom: 30px;
        }
        input[type=text], select {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        input[type=submit] {
            width: 100%;
            background-color: #4CAF50;
            color: white;
            padding: 14px 20px;
            margin: 8px 0;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        input[type=submit]:hover {
            background-color: #45a049;
        }

        div {
            border-radius: 5px;
            background-color: #f2f2f2;
            padding: 20px;
        }
        #submit {
            background-color: #008CBA; /* Green */
            border: none;
            color: white;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
        }
    </style>
</head>
<body>

        <div class="flex-center position-ref full-height">

        <div class="top-right links">



            <a href="">Student Registration</a>
            <!--a href="{{ url('/Instructor/') }}">Instructor Registration</a-->
            <a href="">Course Registration</a>


        </div>

            <div>

                <br>
                <br>
                <h2><marquee>Instructor Registration</marquee></h2>

            <form action="{{ route('instructor.store') }}" method ="POST">
                @csrf

                <label for = "firstname">First name: </label>
                <input type="text" class="form-control" name="firstname" required><br><br>

                <label for = "lastname">Last name:</label>
                <input type="text" class="form-control" name="lastname" required><br><br>

                <label for = "address">Address: </label>
                <input type="text" class="form-control" name="address" required><br><br>

                <label for = "email">Email:</label>
                <input type="text" required class="form-control" name="email" ><br><br>

                <label for = "phoneNo">Phone no:</label>
                <input type="text" class="form-control" name="phoneNo" required><br><br>

                <label for = "subjects">Assigned Subjects: </label>
                <input type="text" class="form-control" name="subjects" required><br><br>



                <input type="submit"  id ="submit" align="center" value="Submit">
                

            </form>
            
            
            </div>

        </div>
</body>
</html>

resources/views/Instructor/edit.blade.php
@extends('layout')
@section('content')

    @if(session()->has('jsAlert'))
        <script>
            alert({{ session()->get('jsAlert') }});
        </script>
    @endif
    <div class="container">

    <form style="margin-left: 400px; margin-right: 400px; margin-top: 100px" method="POST" action="{{ route('instructor.update', $Instructor->id) }}">

        <h1 class="title" style="text-align: center"> Edit Instructor </h1>

        @method('PATCH')
        @csrf

        <div class="field">

            <label class="label" for="name">Instructor ID </label>

            <div class="control">

                <input type="text" class="input" name="id" placeholder="" value="{{ $Instructor->id }}" required>

            </div>

        </div>

        <div class="field">

            <label class="label" for="sport">First Name </label>

            <div class="control">

                <input type="text" class="input" name="firstname" placeholder="" value="{{ $Instructor->firstname }}" required>


            </div>

        </div>
        <div class="field">

            <label class="label" for="sport">Last Name </label>

            <div class="control">

                <input type="text" class="input" name="lastname" placeholder="" value="{{ $Instructor->lastname }}" required>


            </div>

        </div>
        <div class="field">

            <label class="label" for="sport">Address </label>

            <div class="control">

                <input type="text" class="input" name="address" placeholder="" value="{{ $Instructor->address }}" required>


            </div>

            </div>
        <div class="field">

            <label class="label" for="sport">E-mail</label>

            <div class="control">

                <input type="text" class="input" name="email" placeholder="" value="{{ $Instructor->email }}" required>


            </div>

        </div>

         <div class="field">

            <label class="label" for="sport">Phone No </label>

            <div class="control">

                <input type="text" class="input" name="phoneNo" placeholder="" value="{{ $Instructor->phoneNo }}" required>


            </div>

        </div>

         <div class="field">

            <label class="label" for="sport">Subjects </label>

            <div class="control">

                <input type="text" class="input" name="subjects" placeholder="" value="{{ $Instructor->subjects }}" required>


            </div>
            </div>
  <form style="margin-left: 400px; margin-right: 400px; margin-top: 10px" method="POST" action="">

        <div class="field">

            <div class="control">

                <button style="width: 100%" type="submit" class="button is-link">Update Instructor</button>

            </div>

        </div>

    </form>

    <form style="margin-left: 400px; margin-right: 400px; margin-top: 10px" method="POST" action="{{ route('instructor.destroy', $Instructor->id) }}">
            @method('DELETE')
            @csrf


            <div class="field">

                <div class="control">

                    <button style="width: 100%" type="submit" class="button is-link">Remove Instructor</button>

                </div>

            </div>

        </form>

    </div>
@endsection

resources/views/Instructor/show.blade.php
@extends('layout')

@section('content')

    <!DOCTYPE html>
<html lang="">
<head>
    @if(session()->has('jsAlert'))
        <script>
            alert({{ session()->get('jsAlert') }});
        </script>
    @endif
    <style>
        a:link, a:visited {
            background-color: #008CBA;
            color: white;
            padding: 14px 25px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
        }

        a:hover, a:active {
            background-color: red;
        }
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
    <title></title>
</head>
<br style="margin-left: 400px; margin-right: 400px; margin-top: 100px">

<br>

<h1 class="title" style="text-align: center"> Details of Instructor </h1>

@foreach ( $instructor as $instructor)

<table>

    <tr>
        <td>Instructor ID: {{ $instructor->id}}</td>
    </tr>
    <tr>
        <td>First Name: {{ $instructor->firstname }}</td>
    </tr>
    <tr>
        <td>Last Name: {{ $instructor->lastname }}</td>
    </tr>
    <tr>
        <td>Address: {{ $instructor->address }}</td>
    </tr>
    <tr>
        <td>E-mail: {{ $instructor->email }}</td>
    </tr>
    <tr>
        <td>Phone No: {{ $instructor->phoneNo }}</td>
    </tr>
    <tr>
        <td>Subjects: {{ $instructor->subjects }}</td>
    </tr>
    <tr>
        <td>
            <a style=" padding: 5px;" href="{{ route('instructor.edit', $instructor->id) }}">Edit Instructor</a>
       </td> 
          <br>
          <br>
          <tr>
          <td>
            <form  method="POST" action="{{ route('instructor.destroy', $instructor->id) }}">
            @method('DELETE')
            @csrf


            <div class="field">

                <div class="control">

                    <button style = " padding: 5px;" type="submit" class="button is-link">Remove Instructor</button>

                </div>

            </div>

        </form>
        </td>
        
        </tr>
        
       
   
</table>
<br>
<br>
<br>
@endforeach

@endsection

</body>
</html>