routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('course', 'CourseController');


Route::resource('assignments','assignmentsController');

Route::resource('student', 'studentController');

Route::resource('exam', 'ExamController');

//Route::get('/student1', ['uses'=> 'studentController@index']);

Route::get('/st', function() {
    return view('Student.create');

});
    Route::get('/course_home', function () {
        return view('course.courseHome');
    });


    Route::get('/show', function () {
        return view('assignments.show');

    });

    Route::get('/st1', function () {
        return view('Student.index');
    });


    Route::resource('instructor', 'InstructorController');


// Route::get('/instructor', ['uses'=>'InstructorController@index']);

// Route::get('/createInstructor', function(){
//     return view('instructor.create');
// });

// Route::get('/createInstructor/{id}', function(){
//     return view('instructor.create');
// });

app/Course.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Course extends Model
{
    protected $table = "courses";

    public $primarykey="id";

    protected  $guarded = ['id'];
}

app/Http/Controllers/CourseController.php
<?php

namespace App\Http\Controllers;

use Validator;
use App\Course;
use Illuminate\Http\Request;
use Illuminate\Support\MessageBag;
use Illuminate\Support\Facades\session;
use DB;

class CourseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('course.course');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $courses = Course::all();
        return view('course.courseList',compact('courses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
            return DB::transaction(function () use($request){

                $validatedData = $request->validate([
                    'coursename' => ['required', 'max:50'],
                    'coursecode' => ['required', 'max:6'],
                    'enroll' => ['required'],
                    'inLect' => ['required'],
                ]);

                $courses = new Course([
                    'coursename' => $request->get('coursename'),
                    'coursecode' => $request->get('coursecode'),
                    'enroll' => $request->get('enroll'),
                    'inLect' => $request->get('inLect')
                ]);

            $courses->save();

            return redirect()->route('course.create')->with('message', 'Course adding successfull..!');
    });

    }

    /**
     * Display the all resources.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        // $courses = Course::findOrFail($id);
        //return view('course.courseHome');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $courses = Course::findOrFail($id);
         return view('course.courseedit', compact('courses'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $courses = Course::findOrFail($id);
        $courses->update($request->all());
        return redirect()->route('course.create')->with('upmssge', 'Successfully Updated..!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $courses = Course::findOrFail($id);
        $courses -> delete();
        return redirect()->route('course.create')->with('delmssge', 'Successfully deleted..!');
        
    }
}

resources/views/course/course.blade.php
@extends('main')

@section('body')
    <div class="row">
        <div class="col-lg-6 mx-auto">
            <div>
                <br>
                <br>
                <h2>Course Registration</h2>
        
                <form action="{{ route('course.store') }}" method ="POST">
                    @csrf
        
                    <label for = "CourseName">Course name: </label>
                    <input type="text" class="form-control" name="coursename"><br>
        
                    <label for = "CourseCode">Course Code:</label>
                    <input type="text" class="form-control" name="coursecode"><br>
        
                    <label for = "Enrollment">Enrollment Key: </label>
                    <input type="text" class="form-control" name="enroll"><br>
        
                    <label for = "Lectrer">Lecturer Incharge:</label>
                    <input type="text" class="form-control" name="inLect"><br>
        
                    <input type="submit"  id ="submit" align="center" value="Submit"> 
                    <a class="btn btn-primary" id="cancel" href="{{ url('/') }}">Cancel</a>
                </form>
               
            </div>
        
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            
        </div>
        </div>
    </div>
@endsection

resources/views/course/courseHome.blade.php
@extends('main')

@section('body')
<div class="row" style="background-color:lightblue;margin-top:50px;">
    <div class="col-lg-3 mx-auto" style="margin-top:100px;padding-bottom:50px;">
        <h1 style="align:center;color:black;">Course 2019</h1>
        <div>
        <a class="btn btn-primary" style="color:white; background-color:#008CBA;height:35px; width:150px;" href="{{ url('/course') }}">Add Course</a>
        </div>
        <br>
        <br>
        <div>
        <a class="btn btn-primary" style="color:white; background-color:#008CBA;height:35px; width:150px;" href="{{ route('course.create') }}">View Courses</a>
        </div>
    </div>
</div>
@endsection

resources/views/course/courseList.blade.php
@extends('main')

@section('body')
<h1 class="mt-4">Details of Courses</h1>
@if (Session::has('message'))
        <div class="alert alert=success">{{Session::get('message')}}

        </div>
@endif

@if (Session::has('message'))
        <div class="alert alert=success">{{Session::get('message')}}

        </div>
@endif

@if (Session::has('upmssge'))
<div class="alert alert=success">{{Session::get('upmssge')}}

</div>
@endif

@if (Session::has('delmssge'))
        <div class="alert alert=success">{{Session::get('delmssge')}}

        </div>
@endif

<table class="table">
    <tr style="background-color: lightblue;">
        <th>Course Name</th>
        <th>Course Code</th>
        <th>Enrollment key</th>
        <th>Incharge Lecturer</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    @foreach ($courses as $course)
    <tr>
        
        <td>{{$course->coursename}}</td>
        <td>{{$course->coursecode}}</td>
        <td>{{$course->enroll}}</td>
        <td>{{$course->inLect}}</td>
        <td><a class="btn btn-primary" style="color:white; background-color:#008CBA; padding:5px;width:100px;" href="{{ route('course.edit', $course->id) }}">Edit</a>
        </td>
        <td>
        <form method="POST" action="{{route('course.destroy', $course->id)}}">

                @method('DELETE')
                @csrf
        
                        <button class="btn btn-danger" style="color:white; padding:5px;width:100px;" type="submit" class="button is-link">Delete</button>
    
            </form>
        
        </td>        
    </tr>
    @endforeach
</table>
<a class="btn btn-primary" id="cancel" href="{{ url('/') }}">Cancel</a>

@endsection

resources/views/course/courseedit.blade.php
@extends('main')

@section('body')
    
<div>
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<br>
<br>
<h2>Course Details Update</h2>

<form action="{{ route('course.update',$courses->id) }}" method ="POST">
    @method('PATCH')
    @csrf

    <label for = "CourseName">Course name: </label>
    <input type="text" class="input" name="coursename" value="{{ $courses->coursename }}"><br>

    <label for = "CourseCode">Course Code:</label>
    <input type="text" class="input" name="coursecode" value="{{ $courses->coursecode }}"><br>

    <label for = "Enrollment">Enrollment Key: </label>
    <input type="text" class="input" name="enroll" value="{{ $courses->enroll }}"><br>

    <label for = "Lectrer">Lecturer Incharge:</label>
    <input type="text" class="input" name="inLect" value="{{ $courses->inLect }}"><br>

    <input type="submit"  id ="submit" align="center" value="Update">

    <a class="btn btn-primary" id="cancel" href="{{ url('/') }}">Cancel</a>


</form>

</div>

</div>

@endsection